import { Injectable, InternalServerErrorException } from '@nestjs/common';
import Groq from 'groq-sdk';
import type { GenerateRequest } from '../generate/generate.types';
import type { StrategyAgentOutput } from './strategy-agent.service';

export type GeneratedPost = {
  id: number;
  title: string;
  content: string;
  hashtags: string[];
};

export type CreatorAgentOutput = {
  posts: GeneratedPost[];
  summary: string;
};

type RawPost = {
  id?: number | string;
  title?: string;
  content?: string;
  hashtags?: unknown;
};

type RawApiResponse = {
  posts?: unknown;
  summary?: unknown;
};

@Injectable()
export class ContentCreatorService {
  async run(
    input: GenerateRequest,
    strategy: StrategyAgentOutput,
  ): Promise<CreatorAgentOutput> {
    const groq = this.getClient();

    const completion = await groq.chat.completions.create({
      model: process.env.GROQ_CREATOR_MODEL || 'llama-3.1-8b-instant',
      temperature: 0.7,
      response_format: { type: 'json_object' },
      messages: [
        {
          role: 'system',
          content: `
You are Content Creator, a social media content agent.

Return ONLY valid JSON in this exact shape:
{
  "posts": [
    {
      "id": 1,
      "title": "short title",
      "content": "post body",
      "hashtags": ["#one", "#two", "#three"]
    }
  ],
  "summary": "one short sentence"
}

Rules:
- Generate exactly 3 posts.
- Make them clearly different in angle and phrasing.
- Write for the requested platform.
- Follow the strategy brief.
- No markdown code fences.
          `.trim(),
        },
        {
          role: 'user',
          content: `
Topic: ${input.topic}
Platform: ${input.platform}
Brand Name: ${input.brandName || 'Personal Brand'}
Audience: ${input.audience || 'Founders, creators, small business operators'}
Tone: ${input.tone || 'Smart, practical, human'}
CTA Style: ${input.ctaStyle || 'Soft CTA'}

Strategy Angle: ${strategy.angle}
Audience Fit: ${strategy.audienceFit}
Hook Style: ${strategy.hookStyle}
CTA Approach: ${strategy.ctaApproach}
Strategy Brief: ${strategy.brief}

Platform Guidance:
${this.getPlatformGuidance(input.platform)}
          `.trim(),
        },
      ],
    });

    const raw = completion.choices[0]?.message?.content?.trim() || '{}';
    const parsed = this.parseJson(raw);

    const posts = this.extractPosts(parsed.posts);
    const summary =
      typeof parsed.summary === 'string'
        ? parsed.summary
        : 'Generated by Content Creator agent.';

    return {
      posts,
      summary,
    };
  }

  private getClient(): Groq {
    const apiKey = process.env.GROQ_API_KEY;

    if (!apiKey) {
      throw new InternalServerErrorException('Missing GROQ_API_KEY');
    }

    return new Groq({ apiKey });
  }

  private getPlatformGuidance(platform: GenerateRequest['platform']): string {
    switch (platform) {
      case 'LINKEDIN':
        return 'Professional, insight-led, clean paragraph flow, thought leadership tone.';
      case 'YOUTUBE':
        return 'High-curiosity, title-forward, content-teaser style with clear viewer payoff.';
      case 'FACEBOOK':
        return 'Warm, conversational, community-friendly, engagement-oriented.';
      case 'X':
        return 'Short, punchy, sharp, high-signal, fast to skim.';
      case 'INSTAGRAM':
        return 'Caption-friendly, emotionally engaging, visually suggestive, concise.';
      case 'THREADS':
        return 'Casual, human, insight-rich, current, conversational.';
      default:
        return 'Write for a general social audience.';
    }
  }

  private parseJson(raw: string): RawApiResponse {
    const cleaned = raw
      .replace(/^```json/i, '')
      .replace(/^```/, '')
      .replace(/```$/, '')
      .trim();

    try {
      const parsedUnknown: unknown = JSON.parse(cleaned);

      if (!parsedUnknown || typeof parsedUnknown !== 'object') {
        return {};
      }

      return parsedUnknown as RawApiResponse;
    } catch {
      throw new InternalServerErrorException(
        'Content Creator returned invalid JSON.',
      );
    }
  }

  private extractPosts(posts: unknown): GeneratedPost[] {
    if (!Array.isArray(posts)) {
      return [];
    }

    return posts.map((post: unknown, index: number) => {
      const rawPost = this.toRawPost(post);

      return {
        id: Number(rawPost.id ?? index + 1),
        title: String(rawPost.title ?? `Post Option ${index + 1}`),
        content: String(rawPost.content ?? ''),
        hashtags: Array.isArray(rawPost.hashtags)
          ? rawPost.hashtags.map((tag: unknown) => String(tag))
          : [],
      };
    });
  }

  private toRawPost(value: unknown): RawPost {
    if (!value || typeof value !== 'object') {
      return {};
    }

    return value as RawPost;
  }
}
