import { Injectable, InternalServerErrorException } from '@nestjs/common';
import Groq from 'groq-sdk';

export type GeneratedPost = {
  id: number;
  title: string;
  content: string;
  hashtags: string[];
};

export type CreatorAgentOutput = {
  posts: GeneratedPost[];
  summary: string;
};

type RawPost = {
  id?: number | string;
  title?: string;
  content?: string;
  hashtags?: unknown;
};

type RawApiResponse = {
  posts?: unknown;
  summary?: unknown;
};

@Injectable()
export class ContentCreatorService {
  async run(topic: string): Promise<CreatorAgentOutput> {
    const groq = this.getClient();

    const completion = await groq.chat.completions.create({
      model: process.env.GROQ_CREATOR_MODEL || 'llama-3.1-8b-instant',
      temperature: 0.7,
      response_format: { type: 'json_object' },
      messages: [
        {
          role: 'system',
          content: `
You are Content Creator, a social media content agent.

Return ONLY valid JSON in this exact shape:
{
  "posts": [
    {
      "id": 1,
      "title": "short title",
      "content": "post body",
      "hashtags": ["#one", "#two", "#three"]
    }
  ],
  "summary": "one short sentence"
}

Rules:
- Generate exactly 3 posts.
- Make them modern, concise, and engaging.
- Optimize for social media, especially LinkedIn / X style readability.
- Each post should feel different in angle.
- Keep hashtags relevant and not spammy.
- No markdown code fences.
          `.trim(),
        },
        {
          role: 'user',
          content: `Create 3 strong social posts about: ${topic}`,
        },
      ],
    });

    const raw = completion.choices[0]?.message?.content?.trim() || '{}';
    const parsed = this.parseJson(raw);

    const posts = this.extractPosts(parsed.posts);
    const summary =
      typeof parsed.summary === 'string'
        ? parsed.summary
        : 'Generated by Content Creator agent.';

    return {
      posts,
      summary,
    };
  }

  private getClient(): Groq {
    const apiKey = process.env.GROQ_API_KEY;

    if (!apiKey) {
      throw new InternalServerErrorException('Missing GROQ_API_KEY');
    }

    return new Groq({ apiKey });
  }

  private parseJson(raw: string): RawApiResponse {
    const cleaned = raw
      .replace(/^```json/i, '')
      .replace(/^```/, '')
      .replace(/```$/, '')
      .trim();

    try {
      return JSON.parse(cleaned) as RawApiResponse;
    } catch {
      throw new InternalServerErrorException(
        'Content Creator returned invalid JSON.',
      );
    }
  }

  private extractPosts(posts: unknown): GeneratedPost[] {
    if (!Array.isArray(posts)) {
      return [];
    }

    return posts.map((post: unknown, index: number) => {
      const rawPost = this.toRawPost(post);

      return {
        id: Number(rawPost.id ?? index + 1),
        title: String(rawPost.title ?? `Post Option ${index + 1}`),
        content: String(rawPost.content ?? ''),
        hashtags: Array.isArray(rawPost.hashtags)
          ? rawPost.hashtags.map((tag: unknown) => String(tag))
          : [],
      };
    });
  }

  private toRawPost(value: unknown): RawPost {
    if (!value || typeof value !== 'object') {
      return {};
    }

    return value as RawPost;
  }
}
